#!/bin/bash

echo "🔍 Railway Deployment Checklist"
echo "================================"
echo ""
echo "Please verify these settings in your Railway dashboard:"
echo ""
echo "Backend Service Variables:"
echo "  ✓ JWT_SECRET = Kh3Gcp3=ZH2hCf9&gKpG^1T|}{D;[_hM9DIk-1-1R"
echo "  ✓ NODE_ENV = production"
echo "  ✓ DATABASE_URL = (auto-set by Railway)"
echo ""
echo "Backend Service Settings (Settings → Deploy):"
echo "  ✓ Root Directory: backend"
echo "  ✓ Build Command: npm install"
echo "  ✓ Start Command: node src/index.js"
echo ""
echo "After confirming these settings:"
echo "1. Trigger a new deployment in Railway"
echo "2. Watch the logs for:"
echo "   - '📊 Database: [host] (SSL enabled)'"
echo "   - '🚀 Priority Focus Manager API running on port 8080'"
echo "3. Test the health endpoint:"
echo "   curl https://pfm-production-4fb0.up.railway.app/health"
echo ""
echo "Once backend is running, deploy frontend to Vercel!"
